# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

deploy:
  - provider: script
    script: ./docker-build --verbose --config .travis.yml --release github
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:testing"
  - DISTRO="fedora:30"
  - DISTRO="ubuntu:19.04"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mozo
    - gcc
    - git
    - gobject-introspection
    - gtk3
    - intltool
    - make
    - mate-common
    - mate-menus
    - python-gobject
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mozo
    - gettext
    - git
    - gobject-introspection
    - intltool
    - libmate-menu-dev
    - make
    - mate-common
    - python-gi-dev
    - python3

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mozo.git
    - desktop-file-utils
    - gcc
    - git
    - make
    - mate-common 
    - mate-menus-devel
    - pygobject3-devel
    - python3-devel
    - redhat-rpm-config

  ubuntu:
    - gettext
    - git
    - gobject-introspection
    - intltool
    - libmate-menu-dev
    - make
    - mate-common
    - python-gi-dev
    - python3

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

  - cd ${START_DIR}
  - if [ ! -d mate-menus-build ]; then
  -     git clone --depth 1  https://github.com/mate-desktop/mate-menus.git mate-menus-build
  - fi
  - cd mate-menus-build
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./autogen.sh --prefix=/usr
  - fi
  - if [ ${TRAVIS} == "false" ]; then
  -     make clean
  - fi
  - make
  - make install

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mozo-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
